name: Testing

on:
  push:
    branches:
      - main

jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.1

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...
